### ISSUE TITLE
last-tool fails to enforce LAST_Api on last03e

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_tools#27] opened 2023-05-17 08:41 UTC
That's pretty minor but for the record and future maintainability.
```
ocs@last03e:~/matlab/LAST/LAST_Api$ sudo last-tool -n enforce last-software --repo LAST_Api

[SECT] Last-software
[INFO] Forcing ocs.ocs ownership in /home/ocs/matlab/{AstroPack,LAST} ...
[INFO] Fetching the LAST software from github ...
```

but

```
ocs@last03e:~/matlab/LAST/LAST_Api$ sudo last-tool -n enforce last-software --repo LAST_Api

[SECT] Last-software
[INFO] Forcing ocs.ocs ownership in /home/ocs/matlab/{AstroPack,LAST} ...
[INFO] Fetching the LAST software from github ...
ocs@last03e:~/matlab/LAST/LAST_Api$ sudo last-tool -n enforce last-software
...

[INFO] {LAST/LAST_Api}  Fetching from https://github.com/blumzi/LAST_Api into "/home/ocs/matlab/LAST/LAST_Api" ...
[ OK ] {LAST/LAST_Api}  Fetched from "https://github.com/blumzi/LAST_Api" into "/home/ocs/matlab/LAST/LAST_Api".
[ OK ] {LAST/LAST_Api}  Checked out branch=master  in "/home/ocs/matlab/LAST/LAST_Api".
[FAIL] {LAST/LAST_Api}  Could not pull branch=master  in "/home/ocs/matlab/LAST/LAST_Api" (status: 1)
[FAIL] {LAST/LAST_Api}  There is no tracking information for the current branch.
[FAIL] {LAST/LAST_Api}  Please specify which branch you want to merge with.
[FAIL] {LAST/LAST_Api}  See git-pull(1) for details.
[FAIL] {LAST/LAST_Api}  
[FAIL] {LAST/LAST_Api}  git pull <remote> <branch>
[FAIL] {LAST/LAST_Api}  
[FAIL] {LAST/LAST_Api}  If you wish to set tracking information for this branch you can do so with:
[FAIL] {LAST/LAST_Api}  
[FAIL] {LAST/LAST_Api}  git branch --set-upstream-to=origin/<branch> master
[FAIL] {LAST/LAST_Api} 
...
```
Also:
```
ocs@last03e:~/matlab/LAST/LAST_Api$ git status
On branch master
nothing to commit, working tree clean
ocs@last03e:~/matlab/LAST/LAST_Api$ git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master
```
However:
```
ocs@last03e:~/matlab/LAST/LAST_Api$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
ocs@last03e:~/matlab/LAST/LAST_Api$ git pull
Already up to date.
```
and equally ok with `git checkout webapi_transition; git pull`.

**Comment by blumzi** [comment] 2023-05-27 09:01
Couldn't figure out the root cause.
Fixed with ``last-tool -n enforce last-software --repo LAST/LAST_Api --reclone``

**Closed by blumzi** 2023-05-27 09:01 UTC
